apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pg-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.dbUser | quote }}
  password: {{ .Values.postgres.dbPass | quote }}